on: [push]

jobs:
  create_daily_plan_issue:
    runs-on: ubuntu-latest
    name: create daily plan issue
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create daily plan issue action step
        uses: cuixiaorui/create-daily-plan-issue@main
        env:
          TOKEN: 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
        with:
          token: ${{env.TOKEN}}
